### ISSUE TITLE
can the bot be given permission to delete messages?

### ISSUE THREAD

**Issue by Matt30d2000** [Sn0wCrack/saucybot-discord#30] opened 2022-08-23 23:26 UTC
Is it possible to make Saucybot delete the users message after fetching the file(s) and posting the embed?
because otherwise, it's just doubling the amount of messages and clogging up the channels, especially since it works now without even using the command prompt so it's doing it's thing even when people don't intentionally use it.

**Comment by Sn0wCrack** [comment] 2022-08-23 23:49
This is somewhat of a duplicate of #12

I've got plans to add this as a  per-server setting in v2 currently.

**Comment by Sn0wCrack** [comment] 2022-09-26 06:48
I've closed off #12 now as well, if you provide SaucyBot with the "Manage Messages" permission it will remove the embeds from the original post.

**Comment by Sn0wCrack** [comment] 2022-09-28 09:30
@Matt30d2000 

If the new feature solves this issue for you I'll go ahead and close this request, otherwise I can keep this around as v2 feature.

**Closed** 2023-10-13 02:11 UTC
